world: "world"

sounds:
  defaultString: "block.note.harp"
  blocks:
    "24:0": "block.note.snare"
    "80:0": "block.note.basedrum"
    "41:0": "block.note.hat"
    "49:0": "block.note.bass"
  muted: ["35:15"]